### ISSUE TITLE
Include ssl chain certificate

### ISSUE THREAD

**Issue by Szpadel** [ajayyy/ajayyy.github.io#3]
Hello,

Your website is missing chain certificate for let's encrypt (`Let's Encrypt Authority X3`), therefore chrome is blocking access to sponsorblock.

You can validate it using one of the ssl checkers, eg: https://www.sslshopper.com/ssl-checker.html#hostname=https://sponsor.ajay.app/stats

**Comment by ajayyy** [comment]
Hi, did you mean to out this issue on the SponsorBlock repository?

Also, I thought I fixed this. I guess I'll have to try again.
